local locale = GetLocale()
if locale == "zhCN" then
	DebuffTimersLocal = {
		-- [Druid]
		["Faerie Fire"] = "Волшебный огонь",
		["Faerie Fire (Feral)"] = "Волшебный огонь (облик зверя)",
		["Moonfire"] = "Лунный огонь",
		["Soothe Animal"] = "Умиротворение",
		["Challenging Roar"] = "Вызывающий рев",
		["Insect Swarm"] = "Рой насекомых",
		["Growl"] = "Рык",
		["Feral Charge Effect"] = "Звериный рывок - эффект",
		["Pounce Bleed"] = "Кровоточащая рана",
		["Demoralizing Roar"] = "Устрашающий рев",
		["Rake"] = "Глубокая рана",
		["Rip"] = "Разорвать",
		["Entangling Roots"] = "Гнев деревьев",
		["Feral Charge"] = "Звериный рывок",
		["Hibernate"] = "Спячка",
		["Improved Starfire"] = "Улучшенный звездный огонь",
		["Pounce"] = "Наскок",
		["Bash"] = "Оглушить",
		["Nature's Grasp"] = "Хватка природы",
		-- [Hunter]
		["Scorpid Sting"] = "Укус скорпида",
		["Serpent Sting"] = "Укус змеи",
		["Viper Sting"] = "Укус гадюки",
		["Concussive Shot"] = "Контузящий выстрел",
		["Wyvern Sting"] = "Укус виверны",
		["Wing Clip"] = "Подрезать крылья",
		["Explosive Trap Effect"] = "Взрывная ловушка",
		["Immolation Trap Effect"] = "Обжигающая ловушка",
		["Freezing Trap Effect"] = "Замораживающая ловушка",
		["Frost Trap Aura"] = "Ледяная ловушка",
		["Improved Concussive Shot"] = "Улучшенный контузящий выстрел",
		["Intimidation"] = "Устрашение",
		["Scare Beast"] = "Отпугивание зверя",
		["Scatter Shot"] = "Дезориентирующий выстрел",
		["Counterattack"] = "Контратака",
		["Improved Wing Clip"] = "Безжалостно подрезать крылья",
		["Entrapment"] = "Западня",
		["Hunter's Mark"] = "Метка охотника",
		["Explosive Trap"] = "Взрывная ловушка",
		["Immolation Trap"] = "Обжигающая ловушка",
		["Freezing Trap"] = "Замораживающая ловушка",
		["Frost Trap"] = "Ледяная ловушка",
		-- [Mage]
		["Detect Magic"] = "Распознавание магии",
		["Frostbolt"] = "Ледяная стрела",
		["Cone of Cold"] = "Конус холода",
		["Counterspell - Silenced"] = "Антимагия - немота",
		["Fireball"] = "Огненный шар",
		["Pyroblast"] = "Огненная глыба",
		["Ignite"] = "Воспламенение",
		["Flamestrike"] = "Огненный столб",
		["Blast Wave"] = "Взрывная волна",
		["Chilled"] = "Окоченение",
		["Polymorph"] = "Превращение",
		["Polymorph: Cow"] = "Превращение: корова",
		["Polymorph: Pig"] = "Превращение: свинья",
		["Polymorph: Turtle"] = "Превращение: черепаха",
		["Frost Nova"] = "Кольцо льда",
		["Frostbite"] = "Обморожение",
		["Elemental Vulnerability"] = "Уязвимость к стихиям",
		-- [Paladin]
		["Hammer of Justice"] = "Молот правосудия",
		["Repentance"] = "Покаяние",
		["Turn Undead"] = "Изгнание нежити",
		-- [Priest]
		["Blackout"] = "Затмение",
		["Shadow Word: Pain"] = "Слово Тьмы: Боль",
		["Devouring Plague"] = "Всепожирающая чума",
		["Vampiric Embrace"] = "Объятия вампира",
		["Weakened Soul"] = "Ослабленная душа",
		["Holy Fire"] = "Священный огонь",
		["Shackle Undead"] = "Сковывание нежити",
		["Psychic Scream"] = "Ментальный крик",
		["Mind Flay"] = "Пытка разума",
		["Mind Control"] = "Контроль над разумом",
		-- [Rogue]
		["Expose Armor"] = "破甲",
		["Rupture"] = "割裂",
		["Garrote"] = "绞喉",
		["Riposte"] = "还击",
		["Crippling Poison"] = "Калечащий яд",
		["Deadly Poison"] = "Смертельный яд",
		["Kick - Silenced"] = "Пинок - немота",
		["Gouge"] = "凿击",
		["Blind"] = "致盲",
		["Sap"] = "闷棍",
		["Kidney Shot"] = "肾击",
		["Cheap Shot"] = "偷袭",
		-- [Shaman]
		["Frost Shock"] = "Ледяной шок",
		["Flame Shock"] = "Огненный шок",
		["Frostbrand Weapon"] = "Оружие ледяного клейма",
		["Stormstrike"] = "Удар бури",
		-- [Warlock]
		["Pyroclasm"] = "火焰冲击",
		["Aftermath"] = "清算",
		["Shadowburn"] = "暗影灼烧",
		["Immolate"] = "献祭",
		["Corruption"] = "腐蚀术",
		["Curse of Agony"] = "痛苦诅咒",
		["Curse of Exhaustion"] = "疲劳诅咒",
		["Curse of the Elements"] = "元素诅咒",
		["Curse of Shadow"] = "暗影诅咒",
		["Curse of Tongues"] = "语言诅咒",
		["Curse of Weakness"] = "虚弱诅咒",
		["Curse of Recklessness"] = "鲁莽诅咒",
		["Curse of Doom"] = "厄运诅咒",
		["Siphon Life"] = "生命虹吸",
		["Shadow Vulnerability"] = "Власть над Тьмой",
		["Spell Lock"] = "法术封锁",
		["Inferno Effect"] = "Пробуждение инфернала",
		["Cripple"] = "Увечье",
		["Death Coil"] = "死亡缠绕",
		["Seduction"] = "诱惑",
		["Banish"] = "Изгнание",
		["Fear"] = "恐惧",
		["Howl of Terror"] = "恐惧嚎叫",
		["Drain Mana"] = "吸取法力",
		["Drain Life"] = "吸取生命",
		["Drain Soul"] = "吸取灵魂",
		["Tainted Blood Effect"] = "生命通道",
		-- [Warrior]
		["Disarm"] = "Обезоруживание",
		["Mortal Strike"] = "Смертельный удар",
		["Thunder Clap"] = "Удар грома",
		["Taunt"] = "Провокация",
		["Mocking Blow"] = "Дразнящий удар",
		["Demoralizing Shout"] = "Деморализующий крик",
		["Challenging Shout"] = "Вызывающий крик",
		["Sunder Armor"] = "Раскол брони",
		["Rend"] = "Кровопускание",
		["Hamstring"] = "Подрезать сухожилия",
		["Improved Hamstring"] = "Улучшенное подрезание сухожилий",
		["Piercing Howl"] = "Пронзительный вой",
		["Charge Stun"] = "Атака-оглушение",
		["Intercept Stun"] = "Перехват",
		["Mace Specialization"] = "Специализация на одноручном оружии",
		["Intimidating Shout"] = "Устрашающий крик",
		["Revenge Stun"] = "Реванш - оглушение",
		["Concussion Blow"] = "Оглушающий удар",
		-- [General]
		["Sleep"] = "Сон",
		["Net-o-Matic"] = "Сетестрел",
		["Reckless Charge"] = "Безрассудная атака",
		["War Stomp"] = "战争践踏",
		-- [Parser]
		["(.-)%(Rank (%d+)%)"] = "(.-)%(等级 (%d+)%)"
		["Rank (%d+)"] = "等级 (%d+)"
		["You fail to %a+ (.*):.*"] = "Вам не удалось %a+ (.*):.*",
		["is immune to your (.*)%."] = "обладает невосприимчивостью к вашему заклинанию \"(.*)\".%.",
		["Your (.*) missed"] = "Ваше заклинание (.*) не попадает по",
		["Your (.*) was resisted"] = "сопротивляется вашему заклинанию \"(.*)\".%.",
		["Your (.*) was evaded"] = "Ваше заклинание (.*) не достигает",
		["Your (.*) was dodged"] = "уклоняется от вашего заклинания \"(.*)\".%.",
		["Your (.*) was deflected"] = "отклоняет ваше заклинание \"(.*)\".%.",
		["Your (.*) is reflected"] = "отражает ваше заклинание \"(.*)\".%.",
		["Your (.*) is parried"] = "парирует вашу способность \"(.*)\".%.",
		["(.+) fades from (.+)%."] = "(.+)效果从(.+)身上消失了。",
		["(.+)'s (.+) is removed%."] = "(.+) теряет (.+)%.",
		["(.+) is afflicted by (.+)%."] = "(.+)受到了(.+)效果的影响。",
	}

elseif locale == "ruRU" then
	DebuffTimersLocal = {
		-- [Druid]
		["Faerie Fire"] = "Волшебный огонь",
		["Faerie Fire (Feral)"] = "Волшебный огонь (облик зверя)",
		["Moonfire"] = "Лунный огонь",
		["Soothe Animal"] = "Умиротворение",
		["Challenging Roar"] = "Вызывающий рев",
		["Insect Swarm"] = "Рой насекомых",
		["Growl"] = "Рык",
		["Feral Charge Effect"] = "Звериный рывок - эффект",
		["Pounce Bleed"] = "Кровоточащая рана",
		["Demoralizing Roar"] = "Устрашающий рев",
		["Rake"] = "Глубокая рана",
		["Rip"] = "Разорвать",
		["Entangling Roots"] = "Гнев деревьев",
		["Feral Charge"] = "Звериный рывок",
		["Hibernate"] = "Спячка",
		["Improved Starfire"] = "Улучшенный звездный огонь",
		["Pounce"] = "Наскок",
		["Bash"] = "Оглушить",
		["Nature's Grasp"] = "Хватка природы",
		-- [Hunter]
		["Scorpid Sting"] = "Укус скорпида",
		["Serpent Sting"] = "Укус змеи",
		["Viper Sting"] = "Укус гадюки",
		["Concussive Shot"] = "Контузящий выстрел",
		["Wyvern Sting"] = "Укус виверны",
		["Wing Clip"] = "Подрезать крылья",
		["Explosive Trap Effect"] = "Взрывная ловушка",
		["Immolation Trap Effect"] = "Обжигающая ловушка",
		["Freezing Trap Effect"] = "Замораживающая ловушка",
		["Frost Trap Aura"] = "Ледяная ловушка",
		["Improved Concussive Shot"] = "Улучшенный контузящий выстрел",
		["Intimidation"] = "Устрашение",
		["Scare Beast"] = "Отпугивание зверя",
		["Scatter Shot"] = "Дезориентирующий выстрел",
		["Counterattack"] = "Контратака",
		["Improved Wing Clip"] = "Безжалостно подрезать крылья",
		["Entrapment"] = "Западня",
		["Hunter's Mark"] = "Метка охотника",
		["Explosive Trap"] = "Взрывная ловушка",
		["Immolation Trap"] = "Обжигающая ловушка",
		["Freezing Trap"] = "Замораживающая ловушка",
		["Frost Trap"] = "Ледяная ловушка",
		-- [Mage]
		["Detect Magic"] = "Распознавание магии",
		["Frostbolt"] = "Ледяная стрела",
		["Cone of Cold"] = "Конус холода",
		["Counterspell - Silenced"] = "Антимагия - немота",
		["Fireball"] = "Огненный шар",
		["Pyroblast"] = "Огненная глыба",
		["Ignite"] = "Воспламенение",
		["Flamestrike"] = "Огненный столб",
		["Blast Wave"] = "Взрывная волна",
		["Chilled"] = "Окоченение",
		["Polymorph"] = "Превращение",
		["Polymorph: Cow"] = "Превращение: корова",
		["Polymorph: Pig"] = "Превращение: свинья",
		["Polymorph: Turtle"] = "Превращение: черепаха",
		["Frost Nova"] = "Кольцо льда",
		["Frostbite"] = "Обморожение",
		["Elemental Vulnerability"] = "Уязвимость к стихиям",
		-- [Paladin]
		["Hammer of Justice"] = "Молот правосудия",
		["Repentance"] = "Покаяние",
		["Turn Undead"] = "Изгнание нежити",
		-- [Priest]
		["Blackout"] = "Затмение",
		["Shadow Word: Pain"] = "Слово Тьмы: Боль",
		["Devouring Plague"] = "Всепожирающая чума",
		["Vampiric Embrace"] = "Объятия вампира",
		["Weakened Soul"] = "Ослабленная душа",
		["Holy Fire"] = "Священный огонь",
		["Shackle Undead"] = "Сковывание нежити",
		["Psychic Scream"] = "Ментальный крик",
		["Mind Flay"] = "Пытка разума",
		["Mind Control"] = "Контроль над разумом",
		-- [Rogue]
		["Expose Armor"] = "Ослабление доспеха",
		["Rupture"] = "Рваная рана",
		["Garrote"] = "Гаррота",
		["Riposte"] = "Ответный удар",
		["Crippling Poison"] = "Калечащий яд",
		["Deadly Poison"] = "Смертельный яд",
		["Kick - Silenced"] = "Пинок - немота",
		["Gouge"] = "Парализующий удар",
		["Blind"] = "Ослепление",
		["Sap"] = "Ошеломление",
		["Kidney Shot"] = "Удар по почкам",
		["Cheap Shot"] = "Подлый трюк",
		-- [Shaman]
		["Frost Shock"] = "Ледяной шок",
		["Flame Shock"] = "Огненный шок",
		["Frostbrand Weapon"] = "Оружие ледяного клейма",
		["Stormstrike"] = "Удар бури",
		-- [Warlock]
		["Pyroclasm"] = "Пироклазм",
		["Aftermath"] = "Глубокий ожог души",
		["Shadowburn"] = "Ожог Тьмы",
		["Immolate"] = "Жертвенный огонь",
		["Corruption"] = "Порча",
		["Curse of Agony"] = "Бич агонии",
		["Curse of Exhaustion"] = "Проклятие изнеможения",
		["Curse of the Elements"] = "Проклятие стихий",
		["Curse of Shadow"] = "Проклятие тени",
		["Curse of Tongues"] = "Проклятие косноязычия",
		["Curse of Weakness"] = "Проклятие слабости",
		["Curse of Recklessness"] = "Проклятие безрассудства",
		["Curse of Doom"] = "Рок",
		["Siphon Life"] = "Вытягивание жизни",
		["Shadow Vulnerability"] = "Власть над Тьмой",
		["Spell Lock"] = "Запрет чар",
		["Inferno Effect"] = "Пробуждение инфернала",
		["Cripple"] = "Увечье",
		["Death Coil"] = "Лик смерти",
		["Seduction"] = "Соблазн",
		["Banish"] = "Изгнание",
		["Fear"] = "Страх",
		["Howl of Terror"] = "Вой ужаса",
		["Drain Mana"] = "Похищение маны",
		["Drain Life"] = "Похищение жизни",
		["Drain Soul"] = "Похищение души",
		["Tainted Blood Effect"] = "Эффект порченой крови",
		-- [Warrior]
		["Disarm"] = "Обезоруживание",
		["Mortal Strike"] = "Смертельный удар",
		["Thunder Clap"] = "Удар грома",
		["Taunt"] = "Провокация",
		["Mocking Blow"] = "Дразнящий удар",
		["Demoralizing Shout"] = "Деморализующий крик",
		["Challenging Shout"] = "Вызывающий крик",
		["Sunder Armor"] = "Раскол брони",
		["Rend"] = "Кровопускание",
		["Hamstring"] = "Подрезать сухожилия",
		["Improved Hamstring"] = "Улучшенное подрезание сухожилий",
		["Piercing Howl"] = "Пронзительный вой",
		["Charge Stun"] = "Атака-оглушение",
		["Intercept Stun"] = "Перехват",
		["Mace Specialization"] = "Специализация на одноручном оружии",
		["Intimidating Shout"] = "Устрашающий крик",
		["Revenge Stun"] = "Реванш - оглушение",
		["Concussion Blow"] = "Оглушающий удар",
		-- [General]
		["Sleep"] = "Сон",
		["Net-o-Matic"] = "Сетестрел",
		["Reckless Charge"] = "Безрассудная атака",
		["War Stomp"] = "Громовая поступь",
		-- [Parser]
		["You fail to %a+ (.*):.*"] = "Вам не удалось %a+ (.*):.*",
		["is immune to your (.*)%."] = "обладает невосприимчивостью к вашему заклинанию \"(.*)\".%.",
		["Your (.*) missed"] = "Ваше заклинание (.*) не попадает по",
		["Your (.*) was resisted"] = "сопротивляется вашему заклинанию \"(.*)\".%.",
		["Your (.*) was evaded"] = "Ваше заклинание (.*) не достигает",
		["Your (.*) was dodged"] = "уклоняется от вашего заклинания \"(.*)\".%.",
		["Your (.*) was deflected"] = "отклоняет ваше заклинание \"(.*)\".%.",
		["Your (.*) is reflected"] = "отражает ваше заклинание \"(.*)\".%.",
		["Your (.*) is parried"] = "парирует вашу способность \"(.*)\".%.",
		["(.+) fades from (.+)%."] = "Действие эффекта (.+) наложенного на (.+) заканчивается%.",
		["(.+)'s (.+) is removed%."] = "(.+) теряет (.+)%.",
		["(.+) is afflicted by (.+)%."] = "(.+) находится под воздействием эффекта (.+)%.",
	}
else
	DebuffTimersLocal = {
		-- Druid
-- ["Faerie Fire"] = "Faerie Fire",
-- ["Faerie Fire (Feral)"] = "Faerie Fire (Feral)",
-- ["Moonfire"] = "Moonfire",
-- ["Soothe Animal"] = "Soothe Animal",
-- ["Challenging Roar"] = "Challenging Roar",
-- ["Insect Swarm"] = "Insect Swarm",
-- ["Growl"] = "Growl",
-- ["Feral Charge Effect"] = "Feral Charge Effect",
-- ["Pounce Bleed"] = "Pounce Bleed",
-- ["Demoralizing Roar"] = "Demoralizing Roar",
-- ["Rake"] = "Rake",
-- ["Rip"] = "Rip",
-- ["Entangling Roots"] = "Entangling Roots",
-- ["Feral Charge"] = "Feral Charge",
-- ["Hibernate"] = "Hibernate",
-- ["Improved Starfire"] = "Improved Starfire",
-- ["Pounce"] = "Pounce",
-- ["Bash"] = "Bash",
-- ["Nature's Grasp"] = "Nature's Grasp",

-- 		-- Hunter
-- ["Scorpid Sting"] = "Scorpid Sting",
-- ["Serpent Sting"] = "Serpent Sting",
-- ["Viper Sting"] = "Viper Sting",
-- ["Concussive Shot"] = "Concussive Shot",
-- ["Wyvern Sting"] = "Wyvern Sting",
-- ["Wing Clip"] = "Wing Clip",
-- ["Explosive Trap Effect"] = "Explosive Trap Effect",
-- ["Immolation Trap Effect"] = "Immolation Trap Effect",
-- ["Freezing Trap Effect"] = "Freezing Trap Effect",
-- ["Frost Trap Aura"] = "Frost Trap Aura",
-- ["Improved Concussive Shot"] = "Improved Concussive Shot",
-- ["Intimidation"] = "Intimidation",
-- ["Scare Beast"] = "Scare Beast",
-- ["Scatter Shot"] = "Scatter Shot",
-- ["Counterattack"] = "Counterattack",
-- ["Improved Wing Clip"] = "Improved Wing Clip",
-- ["Entrapment"] = "Entrapment",
-- ["Hunter's Mark"] = "Hunter's Mark",
-- ["Explosive Trap"] = "Explosive Trap",
-- ["Immolation Trap"] = "Immolation Trap",
-- ["Freezing Trap"] = "Freezing Trap",
-- ["Frost Trap"] = "Frost Trap",

-- 		--Mage
-- ["Detect Magic"] = "Detect Magic",
-- ["Frostbolt"] = "Frostbolt",
-- ["Cone of Cold"] = "Cone of Cold",
-- ["Counterspell - Silenced"] = "Counterspell - Silenced",
-- ["Fireball"] = "Fireball",
-- ["Pyroblast"] = "Pyroblast",
-- ["Ignite"] = "Ignite",
-- ["Flamestrike"] = "Flamestrike",
-- ["Blast Wave"] = "Blast Wave",
-- ["Chilled"] = "Chilled",
-- ["Polymorph"] = "Polymorph",
-- ["Polymorph: Cow"] = "Polymorph: Cow",
-- ["Polymorph: Pig"] = "Polymorph: Pig",
-- ["Polymorph: Turtle"] = "Polymorph: Turtle",
-- ["Frost Nova"] = "Frost Nova",
-- ["Frostbite"] = "Frostbite",
-- ["Elemental Vulnerability"] = "Elemental Vulnerability",

-- 		--Paladin
-- ["Hammer of Justice"] = "Hammer of Justice",
-- ["Repentance"] = "Repentance",
-- ["Turn Undead"] = "Turn Undead",

-- 		--Priest
-- ["Blackout"] = "Blackout",
-- ["Shadow Word: Pain"] = "Shadow Word: Pain",
-- ["Devouring Plague"] = "Devouring Plague",
-- ["Vampiric Embrace"] = "Vampiric Embrace",
-- ["Weakened Soul"] = "Weakened Soul",
-- ["Holy Fire"] = "Holy Fire",
-- ["Shackle Undead"] = "Shackle Undead",
-- ["Psychic Scream"] = "Psychic Scream",
-- ["Mind Flay"] = "Mind Flay",
-- ["Mind Control"] = "Mind Control",

-- 		--Rogue
-- ["Expose Armor"] = "Expose Armor",
-- ["Rupture"] = "Rupture",
-- ["Garrote"] = "Garrote",
-- ["Riposte"] = "Riposte",
-- ["Crippling Poison"] = "Crippling Poison",
-- ["Deadly Poison"] = "Deadly Poison",
-- ["Kick - Silenced"] = "Kick - Silenced",
-- ["Gouge"] = "Gouge",
-- ["Blind"] = "Blind",
-- ["Sap"] = "Sap",
-- ["Kidney Shot"] = "Kidney Shot",
-- ["Cheap Shot"] = "Cheap Shot",

-- 		--Shaman
-- ["Frost Shock"] = "Frost Shock",
-- ["Flame Shock"] = "Flame Shock",
-- ["Frostbrand Weapon"] = "Frostbrand Weapon",
-- ["Stormstrike"] = "Stormstrike",

-- 		--Warlock
-- ["Pyroclasm"] = "Pyroclasm",
-- ["Aftermath"] = "Aftermath",
-- ["Shadowburn"] = "Shadowburn",
-- ["Immolate"] = "Immolate",
-- ["Corruption"] = "Corruption",
-- ["Curse of Agony"] = "Curse of Agony",
-- ["Curse of Exhaustion"] = "Curse of Exhaustion",
-- ["Curse of the Elements"] = "Curse of the Elements",
-- ["Curse of Shadow"] = "Curse of Shadow",
-- ["Curse of Tongues"] = "Curse of Tongues",
-- ["Curse of Weakness"] = "Curse of Weakness",
-- ["Curse of Recklessness"] = "Curse of Recklessness",
-- ["Curse of Doom"] = "Curse of Doom",
-- ["Siphon Life"] = "Siphon Life",
-- ["Shadow Vulnerability"] = "Shadow Vulnerability",
-- ["Spell Lock"] = "Spell Lock",
-- ["Inferno Effect"] = "Inferno Effect",
-- ["Cripple"] = "Cripple",
-- ["Death Coil"] = "Death Coil",
-- ["Seduction"] = "Seduction",
-- ["Banish"] = "Banish",
-- ["Fear"] = "Fear",
-- ["Howl of Terror"] = "Howl of Terror",
-- ["Drain Mana"] = "Drain Mana",
-- ["Drain Life"] = "Drain Life",
-- ["Drain Soul"] = "Drain Soul",
-- ["Tainted Blood Effect"] = "Tainted Blood Effect",

-- 		-- Warrior
-- ["Disarm"] = "Disarm",
-- ["Mortal Strike"] = "Mortal Strike",
-- ["Thunder Clap"] = "Thunder Clap",
-- ["Taunt"] = "Taunt",
-- ["Mocking Blow"] = "Mocking Blow",
-- ["Demoralizing Shout"] = "Demoralizing Shout",
-- ["Challenging Shout"] = "Challenging Shout",
-- ["Sunder Armor"] = "Sunder Armor",
-- ["Rend"] = "Rend",
-- ["Hamstring"] = "Hamstring",
-- ["Improved Hamstring"] = "Improved Hamstring",
-- ["Piercing Howl"] = "Piercing Howl",
-- ["Charge Stun"] = "Charge Stun",
-- ["Intercept Stun"] = "Intercept Stun",
-- ["Mace Specialization"] = "Mace Specialization",
-- ["Intimidating Shout"] = "Intimidating Shout",
-- ["Revenge Stun"] = "Revenge Stun",
-- ["Concussion Blow"] = "Concussion Blow",

-- 		--General
-- ["Sleep"] = "Sleep",
-- ["Net-o-Matic"] = "Net-o-Matic",
-- ["Reckless Charge"] = "Reckless Charge",
-- ["War Stomp"] = "War Stomp",

-- 		--Parser
-- ["You fail to %a+ (.*):.*"] = "You fail to %a+ (.*):.*",
-- ["is immune to your (.*)%."] = "is immune to your (.*)%.",
-- ["Your (.*) missed"] = "Your (.*) missed",
-- ["Your (.*) was resisted"] = "Your (.*) was resisted",
-- ["Your (.*) was evaded"] = "Your (.*) was evaded",
-- ["Your (.*) was dodged"] = "Your (.*) was dodged",
-- ["Your (.*) was deflected"] = "Your (.*) was deflected",
-- ["Your (.*) is reflected"] = "Your (.*) is reflected",
-- ["Your (.*) is parried"] = "Your (.*) is parried",
-- ["(.+) fades from (.+)%."] = "(.+) fades from (.+)%.",
-- ["(.+)'s (.+) is removed%."] = "(.+)'s (.+) is removed%.",
-- ["(.+) is afflicted by (.+)%."] = "(.+) is afflicted by (.+)%.",
	}
end
