local locale = GetLocale()
if locale == "zhCN" then
	DebuffTimersLocal = {
		-- Druid
		["Волшебный огонь"] = "Faerie Fire",
		["Волшебный огонь (облик зверя)"] = "Faerie Fire (Feral)",
		["Лунный огонь"] = "Moonfire",
		["Умиротворение"] = "Soothe Animal",
		["Вызывающий рев"] = "Challenging Roar",
		["Рой насекомых"] = "Insect Swarm",
		["Рык"] = "Growl",
		["Звериный рывок - эффект"] = "Feral Charge Effect",
		["Кровоточащая рана"] = "Pounce Bleed",
		["Устрашающий рев"] = "Demoralizing Roar",
		["Глубокая рана"] = "Rake",
		["Разорвать"] = "Rip",
		["Гнев деревьев"] = "Entangling Roots",
		["Звериный рывок"] = "Feral Charge",
		["Спячка"] = "Hibernate",
		["Улучшенный звездный огонь"] = "Improved Starfire",
		["Наскок"] = "Pounce",
		["Оглушить"] = "Bash",
		["Хватка природы"] = "Nature's Grasp",

		-- Hunter
		["Укус скорпида"] = "Scorpid Sting",
		["Укус змеи"] = "Serpent Sting",
		["Укус гадюки"] = "Viper Sting",
		["Контузящий выстрел"] = "Concussive Shot",
		["Укус виверны"] = "Wyvern Sting",
		["Подрезать крылья"] = "Wing Clip",
		["Взрывная ловушка"] = "Explosive Trap Effect",
		["Обжигающая ловушка"] = "Immolation Trap Effect",
		["Замораживающая ловушка"] = "Freezing Trap Effect",
		["Ледяная ловушка"] = "Frost Trap Aura",
		["Улучшенный контузящий выстрел"] = "Improved Concussive Shot",
		["Устрашение"] = "Intimidation",
		["Отпугивание зверя"] = "Scare Beast",
		["Дезориентирующий выстрел"] = "Scatter Shot",
		["Контратака"] = "Counterattack",
		["Безжалостно подрезать крылья"] = "Improved Wing Clip",
		["Западня"] = "Entrapment",
		["Метка охотника"] = "Hunter's Mark",
		["Взрывная ловушка"] = "Explosive Trap",
		["Обжигающая ловушка"] = "Immolation Trap",
		["Замораживающая ловушка"] = "Freezing Trap",
		["Ледяная ловушка"] = "Frost Trap",

		--Mage
		["Распознавание магии"] = "Detect Magic",
		["Ледяная стрела"] = "Frostbolt",
		["Конус холода"] = "Cone of Cold",
		["Антимагия - немота"] = "Counterspell - Silenced",
		["Огненный шар"] = "Fireball",
		["Огненная глыба"] = "Pyroblast",
		["Воспламенение"] = "Ignite",
		["Огненный столб"] = "Flamestrike",
		["Взрывная волна"] = "Blast Wave",
		["Окоченение"] = "Chilled",
		["Превращение"] = "Polymorph",
		["Превращение: корова"] = "Polymorph: Cow",
		["Превращение: свинья"] = "Polymorph: Pig",
		["Превращение: черепаха"] = "Polymorph: Turtle",
		["Кольцо льда"] = "Frost Nova",
		["Обморожение"] = "Frostbite",
		["Уязвимость к стихиям"] = "Elemental Vulnerability",

		--Paladin
		["Молот правосудия"] = "Hammer of Justice",
		["Покаяние"] = "Repentance",
		["Изгнание нежити"] = "Turn Undead",

		--Priest
		["Затмение"] = "Blackout",
		["Слово Тьмы: Боль"] = "Shadow Word: Pain",
		["Всепожирающая чума"] = "Devouring Plague",
		["Объятия вампира"] = "Vampiric Embrace",
		["Ослабленная душа"] = "Weakened Soul",
		["Священный огонь"] = "Holy Fire",
		["Сковывание нежити"] = "Shackle Undead",
		["Ментальный крик"] = "Psychic Scream",
		["Пытка разума"] = "Mind Flay",
		["Контроль над разумом"] = "Mind Control",

		--Rogue
		["破甲"] = "Expose Armor",
		["割裂"] = "Rupture",
		["绞喉"] = "Garrote",
		["还击"] = "Riposte",
		["Калечащий яд"] = "Crippling Poison",
		["Смертельный яд"] = "Deadly Poison",
		["Пинок - немота"] = "Kick - Silenced",
		["凿击"] = "Gouge",
		["致盲"] = "Blind",
		["闷棍"] = "Sap",
		["肾击"] = "Kidney Shot",
		["偷袭"] = "Cheap Shot",

		--Shaman
		["Ледяной шок"] = "Frost Shock",
		["Огненный шок"] = "Flame Shock",
		["Оружие ледяного клейма"] = "Frostbrand Weapon",
		["Удар бури"] = "Stormstrike",

		--Warlock
		["火焰冲击"] = "Pyroclasm",
		["清算"] = "Aftermath",
		["暗影灼烧"] = "Shadowburn",
		["献祭"] = "Immolate",
		["腐蚀术"] = "Corruption",
		["痛苦诅咒"] = "Curse of Agony",
		["疲劳诅咒"] = "Curse of Exhaustion",
		["元素诅咒"] = "Curse of the Elements",
		["暗影诅咒"] = "Curse of Shadow",
		["语言诅咒"] = "Curse of Tongues",
		["虚弱诅咒"] = "Curse of Weakness",
		["鲁莽诅咒"] = "Curse of Recklessness",
		["厄运诅咒"] = "Curse of Doom",
		["生命虹吸"] = "Siphon Life",
		["Власть над Тьмой"] = "Shadow Vulnerability",
		["法术封锁"] = "Spell Lock",
		["Пробуждение инфернала"] = "Inferno Effect",
		["Увечье"] = "Cripple",
		["死亡缠绕"] = "Death Coil",
		["诱惑"] = "Seduction",
		["Изгнание"] = "Banish",
		["恐惧"] = "Fear",
		["恐惧嚎叫"] = "Howl of Terror",
		["吸取法力"] = "Drain Mana",
		["吸取生命"] = "Drain Life",
		["吸取灵魂"] = "Drain Soul",
		["生命通道"] = "Tainted Blood Effect",

		-- Warrior
		["Обезоруживание"] = "Disarm",
		["Смертельный удар"] = "Mortal Strike",
		["Удар грома"] = "Thunder Clap",
		["Провокация"] = "Taunt",
		["Дразнящий удар"] = "Mocking Blow",
		["Деморализующий крик"] = "Demoralizing Shout",
		["Вызывающий крик"] = "Challenging Shout",
		["Раскол брони"] = "Sunder Armor",
		["Кровопускание"] = "Rend",
		["Подрезать сухожилия"] = "Hamstring",
		["Улучшенное подрезание сухожилий"] = "Improved Hamstring",
		["Пронзительный вой"] = "Piercing Howl",
		["Атака-оглушение"] = "Charge Stun",
		["Перехват"] = "Intercept Stun",
		["Специализация на одноручном оружии"] = "Mace Specialization",
		["Устрашающий крик"] = "Intimidating Shout",
		["Реванш - оглушение"] = "Revenge Stun",
		["Оглушающий удар"] = "Concussion Blow",

		--General
		["Сон"] = "Sleep",
		["Сетестрел"] = "Net-o-Matic",
		["Безрассудная атака"] = "Reckless Charge",
		["战争践踏"] = "War Stomp",

		--Parser
		["You fail to %a+ (.*):.*"] = "Вам не удалось %a+ (.*):.*",
		["is immune to your (.*)%."] = "обладает невосприимчивостью к вашему заклинанию \"(.*)\".%.",
		["Your (.*) missed"] = "Ваше заклинание (.*) не попадает по",
		["Your (.*) was resisted"] = "сопротивляется вашему заклинанию \"(.*)\".%.",
		["Your (.*) was evaded"] = "Ваше заклинание (.*) не достигает",
		["Your (.*) was dodged"] = "уклоняется от вашего заклинания \"(.*)\".%.",
		["Your (.*) was deflected"] = "отклоняет ваше заклинание \"(.*)\".%.",
		["Your (.*) is reflected"] = "отражает ваше заклинание \"(.*)\".%.",
		["Your (.*) is parried"] = "парирует вашу способность \"(.*)\".%.",
		["(.+) fades from (.+)%."] = "(.+)效果从(.+)身上消失了。",
		["(.+)'s (.+) is removed%."] = "(.+) теряет (.+)%.",
		["(.+) is afflicted by (.+)%."] = "(.+)受到了(.+)效果的影响。",
	}

elseif locale == "ruRU" then
	DebuffTimersLocal = {
		-- Druid
		["Волшебный огонь"] = "Faerie Fire",
		["Волшебный огонь (облик зверя)"] = "Faerie Fire (Feral)",
		["Лунный огонь"] = "Moonfire",
		["Умиротворение"] = "Soothe Animal",
		["Вызывающий рев"] = "Challenging Roar",
		["Рой насекомых"] = "Insect Swarm",
		["Рык"] = "Growl",
		["Звериный рывок - эффект"] = "Feral Charge Effect",
		["Кровоточащая рана"] = "Pounce Bleed",
		["Устрашающий рев"] = "Demoralizing Roar",
		["Глубокая рана"] = "Rake",
		["Разорвать"] = "Rip",
		["Гнев деревьев"] = "Entangling Roots",
		["Звериный рывок"] = "Feral Charge",
		["Спячка"] = "Hibernate",
		["Улучшенный звездный огонь"] = "Improved Starfire",
		["Наскок"] = "Pounce",
		["Оглушить"] = "Bash",
		["Хватка природы"] = "Nature's Grasp",

		-- Hunter
		["Укус скорпида"] = "Scorpid Sting",
		["Укус змеи"] = "Serpent Sting",
		["Укус гадюки"] = "Viper Sting",
		["Контузящий выстрел"] = "Concussive Shot",
		["Укус виверны"] = "Wyvern Sting",
		["Подрезать крылья"] = "Wing Clip",
		["Взрывная ловушка"] = "Explosive Trap Effect",
		["Обжигающая ловушка"] = "Immolation Trap Effect",
		["Замораживающая ловушка"] = "Freezing Trap Effect",
		["Ледяная ловушка"] = "Frost Trap Aura",
		["Улучшенный контузящий выстрел"] = "Improved Concussive Shot",
		["Устрашение"] = "Intimidation",
		["Отпугивание зверя"] = "Scare Beast",
		["Дезориентирующий выстрел"] = "Scatter Shot",
		["Контратака"] = "Counterattack",
		["Безжалостно подрезать крылья"] = "Improved Wing Clip",
		["Западня"] = "Entrapment",
		["Метка охотника"] = "Hunter's Mark",
		["Взрывная ловушка"] = "Explosive Trap",
		["Обжигающая ловушка"] = "Immolation Trap",
		["Замораживающая ловушка"] = "Freezing Trap",
		["Ледяная ловушка"] = "Frost Trap",

		--Mage
		["Распознавание магии"] = "Detect Magic",
		["Ледяная стрела"] = "Frostbolt",
		["Конус холода"] = "Cone of Cold",
		["Антимагия - немота"] = "Counterspell - Silenced",
		["Огненный шар"] = "Fireball",
		["Огненная глыба"] = "Pyroblast",
		["Воспламенение"] = "Ignite",
		["Огненный столб"] = "Flamestrike",
		["Взрывная волна"] = "Blast Wave",
		["Окоченение"] = "Chilled",
		["Превращение"] = "Polymorph",
		["Превращение: корова"] = "Polymorph: Cow",
		["Превращение: свинья"] = "Polymorph: Pig",
		["Превращение: черепаха"] = "Polymorph: Turtle",
		["Кольцо льда"] = "Frost Nova",
		["Обморожение"] = "Frostbite",
		["Уязвимость к стихиям"] = "Elemental Vulnerability",

		--Paladin
		["Молот правосудия"] = "Hammer of Justice",
		["Покаяние"] = "Repentance",
		["Изгнание нежити"] = "Turn Undead",

		--Priest
		["Затмение"] = "Blackout",
		["Слово Тьмы: Боль"] = "Shadow Word: Pain",
		["Всепожирающая чума"] = "Devouring Plague",
		["Объятия вампира"] = "Vampiric Embrace",
		["Ослабленная душа"] = "Weakened Soul",
		["Священный огонь"] = "Holy Fire",
		["Сковывание нежити"] = "Shackle Undead",
		["Ментальный крик"] = "Psychic Scream",
		["Пытка разума"] = "Mind Flay",
		["Контроль над разумом"] = "Mind Control",

		--Rogue
		["Ослабление доспеха"] = "Expose Armor",
		["Рваная рана"] = "Rupture",
		["Гаррота"] = "Garrote",
		["Ответный удар"] = "Riposte",
		["Калечащий яд"] = "Crippling Poison",
		["Смертельный яд"] = "Deadly Poison",
		["Пинок - немота"] = "Kick - Silenced",
		["Парализующий удар"] = "Gouge",
		["Ослепление"] = "Blind",
		["Ошеломление"] = "Sap",
		["Удар по почкам"] = "Kidney Shot",
		["Подлый трюк"] = "Cheap Shot",

		--Shaman
		["Ледяной шок"] = "Frost Shock",
		["Огненный шок"] = "Flame Shock",
		["Оружие ледяного клейма"] = "Frostbrand Weapon",
		["Удар бури"] = "Stormstrike",

		--Warlock
		["Пироклазм"] = "Pyroclasm",
		["Глубокий ожог души"] = "Aftermath",
		["Ожог Тьмы"] = "Shadowburn",
		["Жертвенный огонь"] = "Immolate",
		["Порча"] = "Corruption",
		["Бич агонии"] = "Curse of Agony",
		["Проклятие изнеможения"] = "Curse of Exhaustion",
		["Проклятие стихий"] = "Curse of the Elements",
		["Проклятие тени"] = "Curse of Shadow",
		["Проклятие косноязычия"] = "Curse of Tongues",
		["Проклятие слабости"] = "Curse of Weakness",
		["Проклятие безрассудства"] = "Curse of Recklessness",
		["Рок"] = "Curse of Doom",
		["Вытягивание жизни"] = "Siphon Life",
		["Власть над Тьмой"] = "Shadow Vulnerability",
		["Запрет чар"] = "Spell Lock",
		["Пробуждение инфернала"] = "Inferno Effect",
		["Увечье"] = "Cripple",
		["Лик смерти"] = "Death Coil",
		["Соблазн"] = "Seduction",
		["Изгнание"] = "Banish",
		["Страх"] = "Fear",
		["Вой ужаса"] = "Howl of Terror",
		["Похищение маны"] = "Drain Mana",
		["Похищение жизни"] = "Drain Life",
		["Похищение души"] = "Drain Soul",
		["Эффект порченой крови"] = "Tainted Blood Effect",

		-- Warrior
		["Обезоруживание"] = "Disarm",
		["Смертельный удар"] = "Mortal Strike",
		["Удар грома"] = "Thunder Clap",
		["Провокация"] = "Taunt",
		["Дразнящий удар"] = "Mocking Blow",
		["Деморализующий крик"] = "Demoralizing Shout",
		["Вызывающий крик"] = "Challenging Shout",
		["Раскол брони"] = "Sunder Armor",
		["Кровопускание"] = "Rend",
		["Подрезать сухожилия"] = "Hamstring",
		["Улучшенное подрезание сухожилий"] = "Improved Hamstring",
		["Пронзительный вой"] = "Piercing Howl",
		["Атака-оглушение"] = "Charge Stun",
		["Перехват"] = "Intercept Stun",
		["Специализация на одноручном оружии"] = "Mace Specialization",
		["Устрашающий крик"] = "Intimidating Shout",
		["Реванш - оглушение"] = "Revenge Stun",
		["Оглушающий удар"] = "Concussion Blow",

		--General
		["Сон"] = "Sleep",
		["Сетестрел"] = "Net-o-Matic",
		["Безрассудная атака"] = "Reckless Charge",
		["Громовая поступь"] = "War Stomp",

		--Parser
		["You fail to %a+ (.*):.*"] = "Вам не удалось %a+ (.*):.*",
		["is immune to your (.*)%."] = "обладает невосприимчивостью к вашему заклинанию \"(.*)\".%.",
		["Your (.*) missed"] = "Ваше заклинание (.*) не попадает по",
		["Your (.*) was resisted"] = "сопротивляется вашему заклинанию \"(.*)\".%.",
		["Your (.*) was evaded"] = "Ваше заклинание (.*) не достигает",
		["Your (.*) was dodged"] = "уклоняется от вашего заклинания \"(.*)\".%.",
		["Your (.*) was deflected"] = "отклоняет ваше заклинание \"(.*)\".%.",
		["Your (.*) is reflected"] = "отражает ваше заклинание \"(.*)\".%.",
		["Your (.*) is parried"] = "парирует вашу способность \"(.*)\".%.",
		["(.+) fades from (.+)%."] = "Действие эффекта (.+) наложенного на (.+) заканчивается%.",
		["(.+)'s (.+) is removed%."] = "(.+) теряет (.+)%.",
		["(.+) is afflicted by (.+)%."] = "(.+) находится под воздействием эффекта (.+)%.",
	}
else
	DebuffTimersLocal = {
		-- Druid
		["Faerie Fire"] = "Faerie Fire",
		["Faerie Fire (Feral)"] = "Faerie Fire (Feral)",
		["Moonfire"] = "Moonfire",
		["Soothe Animal"] = "Soothe Animal",
		["Challenging Roar"] = "Challenging Roar",
		["Insect Swarm"] = "Insect Swarm",
		["Growl"] = "Growl",
		["Feral Charge Effect"] = "Feral Charge Effect",
		["Pounce Bleed"] = "Pounce Bleed",
		["Demoralizing Roar"] = "Demoralizing Roar",
		["Rake"] = "Rake",
		["Rip"] = "Rip",
		["Entangling Roots"] = "Entangling Roots",
		["Feral Charge"] = "Feral Charge",
		["Hibernate"] = "Hibernate",
		["Improved Starfire"] = "Improved Starfire",
		["Pounce"] = "Pounce",
		["Bash"] = "Bash",
		["Nature's Grasp"] = "Nature's Grasp",

		-- Hunter
		["Scorpid Sting"] = "Scorpid Sting",
		["Serpent Sting"] = "Serpent Sting",
		["Viper Sting"] = "Viper Sting",
		["Concussive Shot"] = "Concussive Shot",
		["Wyvern Sting"] = "Wyvern Sting",
		["Wing Clip"] = "Wing Clip",
		["Explosive Trap Effect"] = "Explosive Trap Effect",
		["Immolation Trap Effect"] = "Immolation Trap Effect",
		["Freezing Trap Effect"] = "Freezing Trap Effect",
		["Frost Trap Aura"] = "Frost Trap Aura",
		["Improved Concussive Shot"] = "Improved Concussive Shot",
		["Intimidation"] = "Intimidation",
		["Scare Beast"] = "Scare Beast",
		["Scatter Shot"] = "Scatter Shot",
		["Counterattack"] = "Counterattack",
		["Improved Wing Clip"] = "Improved Wing Clip",
		["Entrapment"] = "Entrapment",
		["Hunter's Mark"] = "Hunter's Mark",
		["Explosive Trap"] = "Explosive Trap",
		["Immolation Trap"] = "Immolation Trap",
		["Freezing Trap"] = "Freezing Trap",
		["Frost Trap"] = "Frost Trap",

		--Mage
		["Detect Magic"] = "Detect Magic",
		["Frostbolt"] = "Frostbolt",
		["Cone of Cold"] = "Cone of Cold",
		["Counterspell - Silenced"] = "Counterspell - Silenced",
		["Fireball"] = "Fireball",
		["Pyroblast"] = "Pyroblast",
		["Ignite"] = "Ignite",
		["Flamestrike"] = "Flamestrike",
		["Blast Wave"] = "Blast Wave",
		["Chilled"] = "Chilled",
		["Polymorph"] = "Polymorph",
		["Polymorph: Cow"] = "Polymorph: Cow",
		["Polymorph: Pig"] = "Polymorph: Pig",
		["Polymorph: Turtle"] = "Polymorph: Turtle",
		["Frost Nova"] = "Frost Nova",
		["Frostbite"] = "Frostbite",
		["Elemental Vulnerability"] = "Elemental Vulnerability",

		--Paladin
		["Hammer of Justice"] = "Hammer of Justice",
		["Repentance"] = "Repentance",
		["Turn Undead"] = "Turn Undead",

		--Priest
		["Blackout"] = "Blackout",
		["Shadow Word: Pain"] = "Shadow Word: Pain",
		["Devouring Plague"] = "Devouring Plague",
		["Vampiric Embrace"] = "Vampiric Embrace",
		["Weakened Soul"] = "Weakened Soul",
		["Holy Fire"] = "Holy Fire",
		["Shackle Undead"] = "Shackle Undead",
		["Psychic Scream"] = "Psychic Scream",
		["Mind Flay"] = "Mind Flay",
		["Mind Control"] = "Mind Control",

		--Rogue
		["Expose Armor"] = "Expose Armor",
		["Rupture"] = "Rupture",
		["Garrote"] = "Garrote",
		["Riposte"] = "Riposte",
		["Crippling Poison"] = "Crippling Poison",
		["Deadly Poison"] = "Deadly Poison",
		["Kick - Silenced"] = "Kick - Silenced",
		["Gouge"] = "Gouge",
		["Blind"] = "Blind",
		["Sap"] = "Sap",
		["Kidney Shot"] = "Kidney Shot",
		["Cheap Shot"] = "Cheap Shot",

		--Shaman
		["Frost Shock"] = "Frost Shock",
		["Flame Shock"] = "Flame Shock",
		["Frostbrand Weapon"] = "Frostbrand Weapon",
		["Stormstrike"] = "Stormstrike",

		--Warlock
		["Pyroclasm"] = "Pyroclasm",
		["Aftermath"] = "Aftermath",
		["Shadowburn"] = "Shadowburn",
		["Immolate"] = "Immolate",
		["Corruption"] = "Corruption",
		["Curse of Agony"] = "Curse of Agony",
		["Curse of Exhaustion"] = "Curse of Exhaustion",
		["Curse of the Elements"] = "Curse of the Elements",
		["Curse of Shadow"] = "Curse of Shadow",
		["Curse of Tongues"] = "Curse of Tongues",
		["Curse of Weakness"] = "Curse of Weakness",
		["Curse of Recklessness"] = "Curse of Recklessness",
		["Curse of Doom"] = "Curse of Doom",
		["Siphon Life"] = "Siphon Life",
		["Shadow Vulnerability"] = "Shadow Vulnerability",
		["Spell Lock"] = "Spell Lock",
		["Inferno Effect"] = "Inferno Effect",
		["Cripple"] = "Cripple",
		["Death Coil"] = "Death Coil",
		["Seduction"] = "Seduction",
		["Banish"] = "Banish",
		["Fear"] = "Fear",
		["Howl of Terror"] = "Howl of Terror",
		["Drain Mana"] = "Drain Mana",
		["Drain Life"] = "Drain Life",
		["Drain Soul"] = "Drain Soul",
		["Tainted Blood Effect"] = "Tainted Blood Effect",

		-- Warrior
		["Disarm"] = "Disarm",
		["Mortal Strike"] = "Mortal Strike",
		["Thunder Clap"] = "Thunder Clap",
		["Taunt"] = "Taunt",
		["Mocking Blow"] = "Mocking Blow",
		["Demoralizing Shout"] = "Demoralizing Shout",
		["Challenging Shout"] = "Challenging Shout",
		["Sunder Armor"] = "Sunder Armor",
		["Rend"] = "Rend",
		["Hamstring"] = "Hamstring",
		["Improved Hamstring"] = "Improved Hamstring",
		["Piercing Howl"] = "Piercing Howl",
		["Charge Stun"] = "Charge Stun",
		["Intercept Stun"] = "Intercept Stun",
		["Mace Specialization"] = "Mace Specialization",
		["Intimidating Shout"] = "Intimidating Shout",
		["Revenge Stun"] = "Revenge Stun",
		["Concussion Blow"] = "Concussion Blow",

		--General
		["Sleep"] = "Sleep",
		["Net-o-Matic"] = "Net-o-Matic",
		["Reckless Charge"] = "Reckless Charge",
		["War Stomp"] = "War Stomp",

		--Parser
		["You fail to %a+ (.*):.*"] = "You fail to %a+ (.*):.*",
		["is immune to your (.*)%."] = "is immune to your (.*)%.",
		["Your (.*) missed"] = "Your (.*) missed",
		["Your (.*) was resisted"] = "Your (.*) was resisted",
		["Your (.*) was evaded"] = "Your (.*) was evaded",
		["Your (.*) was dodged"] = "Your (.*) was dodged",
		["Your (.*) was deflected"] = "Your (.*) was deflected",
		["Your (.*) is reflected"] = "Your (.*) is reflected",
		["Your (.*) is parried"] = "Your (.*) is parried",
		["(.+) fades from (.+)%."] = "(.+) fades from (.+)%.",
		["(.+)'s (.+) is removed%."] = "(.+)'s (.+) is removed%.",
		["(.+) is afflicted by (.+)%."] = "(.+) is afflicted by (.+)%.",
	}
end
